#!/usr/bin/env bash
# Caregist — pre-merge database count checks
# Run BEFORE applying each Wave 2 migration.
# Output is a printable checklist. Execute the SQL in your psql session.
set -euo pipefail

echo "========================================================"
echo " Caregist pre-merge checks — run before Wave 2 merges  "
echo " Timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)             "
echo "========================================================"
echo ""
echo "Connect to prod Neon first:"
echo "  psql \"\$DATABASE_URL\""
echo ""

echo "--------------------------------------------------------"
echo " Forge PR #5 — migration 030 (webhook HMAC encryption)"
echo "--------------------------------------------------------"
echo "Run in psql:"
echo "  SELECT count(*) FROM webhook_subscriptions;"
echo ""
echo "  -> If 0:  migration runs cleanly with no data to re-encrypt."
echo "  -> If >0: migration will HMAC-encrypt existing signing secrets."
echo "            Verify WEBHOOK_SECRET_KEY is set in .env BEFORE applying."
echo ""

echo "--------------------------------------------------------"
echo " Spool PR #9 — migration 031 (user sessions table)"
echo "--------------------------------------------------------"
echo "Run in psql:"
echo "  SELECT to_regclass('public.user_sessions');"
echo ""
echo "  -> If NULL:  table does not exist — migration is safe to apply."
echo "  -> If found: table already exists — skip migration, investigate."
echo ""
echo "NOTE: After this migration merges, all existing users will be"
echo "      force-logged out (expected behaviour; documented in PR #9)."
echo ""

echo "--------------------------------------------------------"
echo " Cinch PR #13 — migration 032 (bcrypt API keys)"
echo "--------------------------------------------------------"
echo "Run in psql:"
echo "  SELECT count(*) FILTER (WHERE key_format = 'plaintext') FROM api_keys;"
echo ""
echo "  -> If 0:  no plaintext keys — migration is a no-op data-wise."
echo "  -> If >0: migration will bcrypt those keys. After merge, affected"
echo "            API key holders must use the raw key value (shown once"
echo "            at creation time). Keys stored only as bcrypt hash after."
echo ""

echo "--------------------------------------------------------"
echo " Trill PR #16 — migration 033 (marketing consent column)"
echo "--------------------------------------------------------"
echo "Run in psql:"
echo "  SELECT column_name FROM information_schema.columns"
echo "    WHERE table_name = 'users' AND column_name = 'marketing_consent';"
echo ""
echo "  -> If no row: column does not exist — safe to apply."
echo "  -> If found:  column already exists — skip migration."
echo ""
echo "NOTE: This is an additive ALTER TABLE — no data loss risk."
echo ""

echo "--------------------------------------------------------"
echo " Quill PR #20 — migration 034 (DSAR — renamed from 030)"
echo "--------------------------------------------------------"
echo "BEFORE applying: confirm the file is named 034_dsar.sql, NOT 030_dsar.sql."
echo "  ls db/migrations/ | grep dsar"
echo ""
echo "  -> Must show: 034_dsar.sql"
echo "  -> If shows 030_dsar.sql: rename on the branch before merging."
echo "     git mv db/migrations/030_dsar.sql db/migrations/034_dsar.sql"
echo ""
echo "Run in psql after confirming filename:"
echo "  SELECT to_regclass('public.dsar_requests');"
echo ""
echo "  -> If NULL:  table does not exist — migration is safe to apply."
echo "  -> If found: table already exists — investigate before applying."
echo ""

echo "========================================================"
echo " All checks passed? Proceed with Wave 2 merge sequence:"
echo "   3a. Forge (#5)  -> 030"
echo "   3b. Spool (#9)  -> 031"
echo "   3c. Cinch (#13) -> 032"
echo "   3d. Trill (#16) -> 033"
echo "   3e. Quill (#20) -> 034"
echo "========================================================"
