const ALLOWED_PLAN_UPGRADES = new Set([
  "alerts-pro",
  "data-starter",
  "data-pro",
  "data-business",
]);

const ALLOWED_PROVIDER_UPGRADES = new Set(["enhanced", "sponsored"]);

/**
 * Accept only the two login continuations generated by CareGist's signup flow.
 * This value may be read from localStorage, so fail closed rather than allowing
 * an arbitrary post-verification redirect.
 */
export function normalizePostVerificationPath(value: string | null | undefined): string | null {
  if (!value) return null;

  let parsed: URL;
  try {
    parsed = new URL(value, "https://caregist.invalid");
  } catch {
    return null;
  }

  if (parsed.origin !== "https://caregist.invalid" || parsed.pathname !== "/login" || parsed.hash) {
    return null;
  }

  const keys = [...parsed.searchParams.keys()];
  if (keys.length === 0) return "/login";
  if (keys.length !== 1) return null;

  const upgrade = parsed.searchParams.get("upgrade");
  if (upgrade && ALLOWED_PLAN_UPGRADES.has(upgrade)) {
    return `/login?upgrade=${encodeURIComponent(upgrade)}`;
  }

  const providerTier = parsed.searchParams.get("provider_tier");
  if (providerTier && ALLOWED_PROVIDER_UPGRADES.has(providerTier)) {
    return `/login?provider_tier=${encodeURIComponent(providerTier)}`;
  }

  return null;
}

