const ALLOWED_PLAN_UPGRADES = new Set([
  "radar-regional",
  "radar-national",
]);

/**
 * Accept only the two login continuations generated by CareGist's signup flow.
 * This value may be read from localStorage, so fail closed rather than allowing
 * an arbitrary post-verification redirect.
 */
export function normalizePostVerificationPath(value: string | null | undefined): string | null {
  if (!value) return null;

  let parsed: URL;
  try {
    parsed = new URL(value, "https://caregist.invalid");
  } catch {
    return null;
  }

  if (parsed.origin !== "https://caregist.invalid" || parsed.pathname !== "/login" || parsed.hash) {
    return null;
  }

  const keys = [...parsed.searchParams.keys()];
  if (keys.length === 0) return "/login";
  if (keys.length !== 1) return null;

  const upgrade = parsed.searchParams.get("upgrade");
  if (upgrade && ALLOWED_PLAN_UPGRADES.has(upgrade)) {
    return `/login?upgrade=${encodeURIComponent(upgrade)}`;
  }

  return null;
}

/** Select the first allowlisted continuation, defaulting to the normal login. */
export function resolvePostVerificationPath(
  ...candidates: Array<string | null | undefined>
): string {
  for (const candidate of candidates) {
    const normalized = normalizePostVerificationPath(candidate);
    if (normalized) return normalized;
  }
  return "/login";
}
